version: '3.7'
services:
  app:
    build:
      args:
        - NODE_ENV=production
        - user=nestjs
        - uid=1001
        - group=nodejs
      context: ../
      dockerfile: docker/Dockerfile
    image: pratamaizzat/undanganio:0.1
    container_name: undangan_app
    restart: always
    working_dir: /app/
    depends_on:
      - db
    ports:
      - 3333:3333
    command: node dist/src/main
    networks:
      - undangan
    

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: undangan_db
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports :
      - 5432:5432
    networks:
      - undangan

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - undangan

networks:
  undangan:
    driver: bridge