on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: Build, test, and deploy

env:
  PNPM_VERSION: 7.2.1

jobs:
  test:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - name: test action step 1
        run: echo "Hallo world"
